<div data-role="page" id="error" data-theme="d" data-title="ERROR">
  <div data-role="header" data-theme="b" data-position="fixed" data-transition="pop">
    <a title="Home" href="/" data-icon="home" data-iconpos="notext">Home</a>
    <h1>Móveis Simonetti</h1>
  </div><!-- /header -->

  <div data-role="content">
    <h1>Error 404</h1>
    <h4>Página não encontrada</h4>
  </div>

  <div data-role="footer" data-theme="b" data-position="fixed" data-transition="pop">
    <h4>Móveis Simonetti - 2005/12</h4>
  </div><!-- /footer -->
</div>