<div data-role="page" id="adicionarPagina" data-theme="d" data-title="Adicionar Página">
  <div data-role="header" data-theme="b" data-position="fixed" data-transition="pop" >
    <a title="Home" href="/" data-icon="home" data-iconpos="notext">Home</a>
    <h1>Móveis Simonetti</h1>
  </div><!-- /header -->
  <div data-role="content">
    <h1>Adicionar Página</h1>
    <form action="" method="post" data-ajax="true">
      <fieldset>
        <input type="hidden" name="status" value="1" />
        <input type="text" name="titulo" placeholder="Titulo da Pagina" /><br/>
        <input type="text" name="nome" placeholder="Nome da Pagina" /><br/>
        <input type="text" name="url" placeholder="URL da Página" /><br/>
        <textarea name="conteudo"></textarea>
        <button aria-disabled="false" type="submit" data-theme="b" name="submit" value="submit-value">Adicionar</button>
      </fieldset>
    </form>
   <div data-role="collapsible" data-theme="a" data-content-theme="a">
   <h3>Termos</h3>
   <p>aljksdgkjasndgjan lgjand fljan lgjnadl fjgnalndfgjknadls,asdlçmasmam sdçlvadmflkvam kmfkamdçl mçalkmdf çlmad</p>
</div>
  </div>
  <div data-role="footer" data-theme="b" data-position="fixed" data-transition="pop">
    <h4>Móveis Simonetti - 2005/12</h4>
  </div><!-- /footer -->
</div>
