<?php
if ($this->view->pagina != null) {
  foreach ($this->view->pagina as $te):
    ?>
    <div data-role="page" id="Pagina" data-theme="d" data-title="<?= $te['titulo']; ?>">

      <div data-role="header" data-theme="b" data-position="fixed">
        <a title="Home" href="/" data-icon="home" data-iconpos="notext">Home</a>
        <h1>Móveis Simonetti - <?= $te['nome']; ?></h1>
      </div><!-- /header -->

      <div data-role="content">

        <?= base64_decode($te['conteudo']); ?>

      </div><!-- /content -->

      <div data-role="footer" data-theme="b" data-position="fixed">
        <h4>Móveis Simonetti - 2005/12</h4>
      </div><!-- /footer -->
    </div><!-- /page two -->
    <?php
  endforeach;
}else {
  ?>

  <div data-role="page" id="Pagina" data-theme="d" data-title="ERROR">

    <div data-role="header" data-theme="b" data-position="fixed">
      <a title="Home" href="/" data-icon="home" data-iconpos="notext">Home</a>
      <h1>Móveis Simonetti - ERROR</h1>
    </div><!-- /header -->

    <div data-role="content">

      <?= $this->view->paginaError;?>

    </div><!-- /content -->

    <div data-role="footer" data-theme="b" data-position="fixed">
      <h4>Móveis Simonetti - 2005/12</h4>
    </div><!-- /footer -->
  </div><!-- /page two -->

<?php } ?>
