<div data-role="page" id="termos" data-title="Termos">

  <div data-role="header" data-theme="c">
    <h1>Termos</h1>
  </div><!-- /header -->
  <div data-role="navbar" data-iconpos="left">
    <ul>
      <li><a href="/" data-theme="a">Home</a></li>
      <li><a href="/cadastro" data-theme="a">Cadastro</a></li>
      <li><a href="/termos" data-theme="a">Termos de Uso</a></li>
      <li><a href="/contato" data-theme="a">Contato</a></li>
      <li><a href="#popupLogin" data-theme="e" data-rel="popup">Login</a></li>
    </ul>
    <div data-role="popup" id="popupLogin" data-theme="a">
      <form method="post" action="/">
        <div style="padding:10px 20px;">
          <h3>Faça o login</h3>
          <label for="un">Usuario:</label>
          <input type="text" name="user" id="un" value="" placeholder="Usuario" data-theme="e" />

          <label for="pw">Senha:</label>
          <input type="password" name="pass" id="pw" value="" placeholder="Senha" data-theme="e" />

          <button type="submit" data-theme="b">Logar</button>
        </div>
      </form>
    </div>
  </div><!-- /navbar -->
  <div data-role="content">
    <h1>Termos de Uso</h1>


  </div>

  <div data-role="footer">
    <h4>&copy; 2012</h4>
  </div><!-- /footer -->
</div><!-- /page -->