<div data-role="page" id="home" data-theme="d" data-title="HOME">
  <div data-role="header" data-theme="b" data-position="fixed" data-transition="pop">
    <a title="Home" href="/" data-icon="home" data-iconpos="notext">Home</a>
    <h1>Móveis Simonetti</h1>
  </div><!-- /header -->

  <div data-role="navbar" >
    <ul>
      <?php
      if ($this->view->menu->count() >= 1) {
        foreach ($this->view->menu as $t):
          ?>
          <li><a href="/pagina/<?= $t['nome'] ?>"><?= $t['nome'] ?></a></li>

        <?php
        endforeach;
      }else {
        ?>
   <li><a href="#"> </a></li>
<?php } ?>

    </ul>
  </div><!-- /navbar -->

  <div data-role="content">


  </div><!-- /content -->

  <div data-role="footer" data-theme="b" data-position="fixed" data-transition="pop">
    <h4>Móveis Simonetti - 2005/12</h4>
  </div><!-- /footer -->
</div>