<!DOCTYPE html>
<html>
  <head>
    <title>MOBILE - DEV</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <?= $this -> getLayout () -> getHeaderStyle () ; ?>
  </head>

  <body>

    <?= $this -> content () ; ?>


    <!-- JavaScript
    ================================================= -->
    <!-- Colocado no final do documento para que as páginas carregar mais rápido -->
    <?= $this -> getLayout () -> getHeaderScript () ; ?>
    <!-- End JavaScript
    ================================================= -->
  </body>
</html>